server:
  port: 8083
  session:
    timeout: 1800
  #address: acount.yayao8.com
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60 
spring: 
  datasource:
    url: jdbc:mysql://39.108.60.100:3306/schedule_job_db
    username: root
    password: liliu
    driver-class-name:  com.mysql.jdbc.Driver  
#  jpa:
#    hibernate:
#      ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL5Dialect   
  redis: 
    host: 39.108.60.100
    password: liliu
    port: 6379 
    database: 3
    timeout: 3000
    pool: 
      min-idle: 100
      max-idle: 300
      max-active: 800 
myPugin:
  projectName: ScheduleJob
  testApi: true 
  session: 
    myDomainName: newzhuan.cn
  quartzJobUrl: http://www.newzhuan.cn/scheduleJob/accept
